"""Public pure-function core for RelaCaTS-v1."""

from .canonicalization import (
    AnswerNormalizationResult,
    CanonicalizationResult,
    CanonicalizationStatus,
    InvalidAnswerError,
    canonicalize_answer,
    canonicalize_answer_value,
    normalize_answer,
    normalize_numeric_answer,
    normalize_option_answer,
)
from .relational_views import (
    DEFAULT_OPTION_LABELS,
    InvalidPermutationError,
    OptionPermutation,
    RelationalView,
    RelationalViewError,
    SamplingBudgetError,
    generate_identity_views,
    generate_option_permutation_views,
    render_multiple_choice_question,
    validate_sampling_budget,
)
from .relssc import (
    InvalidConfidenceError,
    RelSSCError,
    RelSSCResult,
    RelSSCSample,
    UnsupportedV1WeightError,
    ZeroTotalWeightError,
    ZeroWeightPolicy,
    attach_relssc_targets,
    compute_relssc,
)

__all__ = [
    "AnswerNormalizationResult",
    "CanonicalizationResult",
    "CanonicalizationStatus",
    "DEFAULT_OPTION_LABELS",
    "InvalidAnswerError",
    "InvalidConfidenceError",
    "InvalidPermutationError",
    "OptionPermutation",
    "RelSSCError",
    "RelSSCResult",
    "RelSSCSample",
    "RelationalView",
    "RelationalViewError",
    "SamplingBudgetError",
    "UnsupportedV1WeightError",
    "ZeroTotalWeightError",
    "ZeroWeightPolicy",
    "attach_relssc_targets",
    "canonicalize_answer",
    "canonicalize_answer_value",
    "compute_relssc",
    "generate_option_permutation_views",
    "generate_identity_views",
    "normalize_answer",
    "normalize_numeric_answer",
    "normalize_option_answer",
    "render_multiple_choice_question",
    "validate_sampling_budget",
]
